version: "3.9"
services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypossword
      - POSTGRES_DB=postgres
    volumes:
      - db-strage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  db-strage:
